// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/subscription/create": {
            "post": {
                "description": "Создание новой подписки, subscription_id - primary key. user_id и start_date можно не указывать, на них стоит default. end_date также можно не указывать, в бд будет null",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Регистрация новой подписки",
                "parameters": [
                    {
                        "description": "user_id и start_date можно не заполнять",
                        "name": "subscription",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.SubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/delete": {
            "delete": {
                "description": "Удаление подписки по subscription_id",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Удаление подписки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id подписки",
                        "name": "subscription_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/get": {
            "get": {
                "description": "Получение подписки по subscription_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Получение подписки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id подписки",
                        "name": "subscription_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение подписки",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.SubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/getList": {
            "get": {
                "description": "Получение всех подписок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Получение всех подписок",
                "responses": {
                    "200": {
                        "description": "Успешное получение подписки",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subscription-service_internal_entity.SubscriptionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/update": {
            "put": {
                "description": "Обновление подписки, subscription_id - primary key. service_name, user_id не учитывается. start_date можно не указывать, стоит default. end_date также можно не указывать, в бд будет null",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Обновление подписки",
                "parameters": [
                    {
                        "description": "service_name, user_id не учитывается. start_date можно не указывать",
                        "name": "subscription",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.SubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка",
                        "schema": {
                            "$ref": "#/definitions/subscription-service_internal_entity.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "subscription-service_internal_entity.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "subscription-service_internal_entity.SubscriptionRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "subscription_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "subscription-service_internal_entity.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "subscription-service",
	Description:      "CRUDL-операции операции по работке с подписками.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	//LeftDelim:        "{{",
	//RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
